controller_manager:
  ros__parameters:
    update_rate: 100 # Hz


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ackermann_steering_controller:
  ros__parameters:

    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    rear_wheels_names: [back_right_wheel_joint, back_left_wheel_joint]
    front_wheels_names: [front_right_steering_joint, front_left_steering_joint]

    wheelbase: 0.7  # [m]
    front_wheel_track: 0.9144
    rear_wheel_track: 0.9144
    front_wheels_radius: 0.1524
    rear_wheels_radius: 0.1524