controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

      joints:
      - pinion_joint
      - motor_joint

    ackermann_angle_controller:
      type: igvc_control::AckermannAngleController

ackermann_angle_controller:
  ros__parameters:
    # Joint names
    pinion_joint: pinion_joint
    motor_joint: motor_joint

    # Topics
    cmd_vel_topic: /cmd_vel_unstamped
    reference_timeout: 2.0
    calibration_sample_size: 1024

    max_pinion_angle: 15.0

    # Linkage geometry parameters
    pinion_radius: 0.01905
    steering_arm_length: 0.159
    tie_rod_length: 0.1813
    rack_offset_x: -0.100
    rack_neutral_y: 0.2298
    pinion_gear_ratio: 1.652
    wheel_angle: 0.32253
    wheelbase: 0.6096
    track_width: 0.9144
    wheel_radius: 0.1016

